# .travis.yml
language: ruby
rvm:
  - 1.9.3
  - 2.1.0
env:
  - DB=sqlite
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
before_script:
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database de_test'
  - psql -c 'create database de_test' -U postgres